Invoked as: ./configure 
Tclsh: /usr/bin/tclsh
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccheoYZ3.o: in function `main':
/workspaces/RAG-APPLICATION-ISAT/sqlite-src-3490100/conftest__.c:3: undefined reference to `localtime_s'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void localtime_s(void);
int main(void) {
localtime_s();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccQFZFJ2.o: in function `main':
/workspaces/RAG-APPLICATION-ISAT/sqlite-src-3490100/conftest__.c:3: undefined reference to `deflate'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void deflate(void);
int main(void) {
deflate();
return 0;
}
============
Failed: cc -c -O2 -g conftest__.c -o conftest__.o
conftest__.c: In function ‘main’:
conftest__.c:3:12: error: size of array ‘_x’ is negative
    3 | static int _x[sizeof(off_t) == 4 ? 1 : -1] = { 1 };
      |            ^~
child process exited abnormally
============
The failed code was:
#include <sys/types.h>
int main(void) {
static int _x[sizeof(off_t) == 4 ? 1 : -1] = { 1 };
return 0;
}
============
Failed: cc -c -rpath /usr/local/lib -O2 -g conftest__.c -o conftest__.o
cc: error: unrecognized command-line option ‘-rpath’
child process exited abnormally
============
The failed code was:
int main(void) {

return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccLD1sID.o: in function `main':
/workspaces/RAG-APPLICATION-ISAT/sqlite-src-3490100/conftest__.c:3: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void pthread_create(void);
int main(void) {
pthread_create();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccYwPKTs.o: in function `main':
/workspaces/RAG-APPLICATION-ISAT/sqlite-src-3490100/conftest__.c:3: undefined reference to `pthread_mutexattr_init'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void pthread_mutexattr_init(void);
int main(void) {
pthread_mutexattr_init();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccMlc8Kc.o: in function `main':
/workspaces/RAG-APPLICATION-ISAT/sqlite-src-3490100/conftest__.c:3: undefined reference to `tgetent'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void tgetent(void);
int main(void) {
tgetent();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__ -lreadline
/usr/bin/ld: /tmp/ccAG3qvA.o: in function `main':
/workspaces/RAG-APPLICATION-ISAT/sqlite-src-3490100/conftest__.c:3: undefined reference to `tgetent'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void tgetent(void);
int main(void) {
tgetent();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__ -lncurses
/usr/bin/ld: /tmp/ccfvaXfk.o: in function `main':
/workspaces/RAG-APPLICATION-ISAT/sqlite-src-3490100/conftest__.c:3: undefined reference to `readline'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void readline(void);
int main(void) {
readline();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccpZEkGV.o: in function `main':
/workspaces/RAG-APPLICATION-ISAT/sqlite-src-3490100/conftest__.c:3: undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void dlopen(void);
int main(void) {
dlopen();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
conftest__.c:1:13: warning: conflicting types for built-in function ‘ceil’; expected ‘double(double)’ [-Wbuiltin-declaration-mismatch]
    1 | extern void ceil(void);
      |             ^~~~
conftest__.c:1:1: note: ‘ceil’ is declared in header ‘<math.h>’
  +++ |+#include <math.h>
    1 | extern void ceil(void);
/usr/bin/ld: /tmp/cct38gSG.o: in function `main':
/workspaces/RAG-APPLICATION-ISAT/sqlite-src-3490100/conftest__.c:3: undefined reference to `ceil'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void ceil(void);
int main(void) {
ceil();
return 0;
}
============
